# Generated by Django 3.1.3 on 2021-07-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='relative_point',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
